import Head from 'next/head'
import Footer from './Footer'

export default function Layout({ children }) {

    const year = new Date().getFullYear();

    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <title>Count Down App</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {children}

            <Footer year={year} />
        </>
    )
}